print("World!")
print("Navein")
vector = c(1, 2, 3, 4)
print(vector)
matrix(("a"),1,3, byrow = TRUE)
install.packages("tidyverse")
library(tidyverse)
library(tidyquant)
tq_get("AAPL", get = "stock.prices", from = "2024-01-01", to = "2024-02-18")
